In [2]:
import cv2
from keras.models import load_model
import numpy as np
model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    if prediction[0][0]>0.5:
        print("Rock")
    elif prediction[0][1]>0.5:
        print("Paper")
    elif prediction[0][2]>0.5:
        print("Scissors")
    else:
        print("Nothing")
    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()
cv2.waitKey(1)

2022-05-22 22:14:05.962888: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Rock
[[0.64807785 0.00180591 0.07095859 0.27915764]]
Nothing
[[0.07797603 0.09500019 0.01467506 0.8123487 ]]
Paper
[[0.05358617 0.5642731  0.0187143  0.36342654]]
Nothing
[[0.12520525 0.09286516 0.00704266 0.7748869 ]]
Nothing
[[0.06253123 0.09952438 0.00520896 0.8327355 ]]
Nothing
[[0.1690118  0.16632631 0.0145507  0.6501112 ]]
Nothing
[[0.04381632 0.4780512  0.01833431 0.4597982 ]]
Nothing
[[0.01484574 0.4774567  0.00904924 0.49864838]]
Nothing
[[0.02560685 0.08076853 0.05816293 0.83546174]]
Nothing
[[0.02189386 0.14607637 0.02848764 0.80354226]]
Nothing
[[0.01086836 0.2041201  0.00739079 0.7776208 ]]
Nothing
[[0.00785289 0.02589041 0.00206801 0.96418864]]
Nothing
[[0.0412753  0.02651025 0.00388229 0.92833215]]
Nothing
[[0.21884677 0.06880827 0.01834195 0.69400305]]
Rock
[[0.6478617  0.25693113 0.00609132 0.08911588]]
Paper
[[0.00315745 0.9721825  0.01207052 0.01258943]]
Paper
[[0.00963875 0.97230434 0.01125525 0.00680174]]
Nothing
[[0.46841195 0.37596932 0.13864982 0.01696884]]
Rock

-1

: 

'rock'