In [1]:
import cv2
from keras.models import load_model
import numpy as np
model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    if prediction[0][0]>0.5:
        print("Rock")
    elif prediction[0][1]>0.5:
        print("Paper")
    elif prediction[0][2]>0.5:
        print("Scissors")
    else:
        print("Nothing")
    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()
cv2.waitKey(1)

Metal device set to: Apple M1

systemMemory: 8.00 GB
maxCacheSize: 2.67 GB



2022-05-22 15:45:56.037873: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-05-22 15:45:56.038106: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


2022-05-22 15:45:58.390600: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2022-05-22 15:45:58.603266: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Nothing
[[6.5381579e-02 7.1270056e-02 2.8899853e-05 8.6331952e-01]]
Nothing
[[6.0483227e-03 2.6546644e-02 8.2539736e-06 9.6739680e-01]]
Nothing
[[6.8662269e-03 2.9094510e-02 7.7238565e-06 9.6403164e-01]]
Nothing
[[6.7955260e-03 2.5760492e-02 5.0122071e-06 9.6743894e-01]]
Nothing
[[6.0461275e-03 2.0766294e-02 6.9883558e-06 9.7318053e-01]]
Nothing
[[6.2012337e-03 3.0587785e-02 6.9360372e-06 9.6320409e-01]]
Nothing
[[6.0668285e-03 2.2993203e-02 4.8019820e-06 9.7093517e-01]]
Nothing
[[6.1329911e-03 2.5336500e-02 6.2697004e-06 9.6852422e-01]]
Nothing
[[4.589195e-03 2.499559e-02 6.636175e-06 9.704086e-01]]
Nothing
[[4.7123013e-03 2.1029985e-02 6.5872782e-06 9.7425115e-01]]
Nothing
[[7.5362581e-03 2.6443629e-02 7.3618135e-06 9.6601272e-01]]
Nothing
[[4.51410795e-03 1.31541835e-02 6.05477726e-06 9.82325613e-01]]
Nothing
[[5.1918793e-03 1.1740531e-02 5.0929157e-06 9.8306251e-01]]
Nothing
[[6.0569211e-03 1.3665444e-02 6.5077065e-06 9.8027122e-01]]
Nothing
[[5.6854174e-03 1.0080641e-02 7.2332568e

AttributeError: 'cv2.VideoCapture' object has no attribute 'videoCapture'

: 