In [3]:
import cv2
from keras.models import load_model
import numpy as np
model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    if prediction[0][0]>0.5:
        print("Rock")
    elif prediction[0][1]>0.5:
        print("Paper")
    elif prediction[0][2]>0.5:
        print("Scissors")
    else:
        print("Nothing")
    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()

Metal device set to: Apple M1

systemMemory: 8.00 GB
maxCacheSize: 2.67 GB



2022-05-20 10:41:45.337284: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-05-20 10:41:45.337601: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


2022-05-20 10:41:47.733579: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2022-05-20 10:41:48.023941: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Scissors
[[1.2731525e-08 1.4149853e-07 9.9999535e-01 4.5096303e-06]]
Scissors
[[1.3156902e-10 1.8343022e-02 9.8149937e-01 1.5762358e-04]]
Scissors
[[1.9663063e-10 7.5124768e-03 9.9231976e-01 1.6777497e-04]]
Scissors
[[1.3284179e-10 2.2117499e-02 9.7769427e-01 1.8824276e-04]]
Scissors
[[1.5359924e-10 5.4204945e-02 9.4555593e-01 2.3915259e-04]]
Scissors
[[2.4682523e-10 1.0118975e-02 9.8947096e-01 4.1013560e-04]]
Scissors
[[1.2438628e-10 8.5841361e-03 9.9097145e-01 4.4440248e-04]]
Scissors
[[6.6891298e-11 2.7248854e-02 9.7238332e-01 3.6784710e-04]]
Scissors
[[8.3633586e-11 6.9389441e-03 9.9278694e-01 2.7405270e-04]]
Scissors
[[4.8397120e-11 6.2212921e-03 9.9356186e-01 2.1685159e-04]]
Scissors
[[5.9024882e-11 8.9039328e-03 9.9079567e-01 3.0038197e-04]]
Scissors
[[1.1019073e-11 7.6693995e-03 9.9219924e-01 1.3133700e-04]]
Scissors
[[3.9159009e-11 9.0880450e-03 9.9073607e-01 1.7582520e-04]]
Scissors
[[5.7240435e-11 1.1309188e-02 9.8844320e-01 2.4760576e-04]]
Scissors
[[6.2438422e-11 3.4045275

: 

In [2]:
import numpy as np
np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        ...,

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)